FROM node:22-bookworm-slim

ENV NEXT_TELEMETRY_DISABLED=1

WORKDIR /app

# Python runtime for Day3/Day4 batch scripts
RUN apt-get update \
  && apt-get install -y --no-install-recommends python3 python3-venv ca-certificates \
  && rm -rf /var/lib/apt/lists/*

COPY package*.json ./
RUN npm ci --include=dev

COPY requirements.txt ./
RUN python3 -m venv /opt/venv \
  && /opt/venv/bin/pip install --no-cache-dir --upgrade pip \
  && /opt/venv/bin/pip install --no-cache-dir -r requirements.txt

COPY . .

ARG NEXT_PUBLIC_FIREBASE_API_KEY=AIzaSyCggSf0BzgsmEUM6PCPDbF7KWz2GmcSaZ8
ARG NEXT_PUBLIC_FIREBASE_AUTH_DOMAIN=nexus0101-35b17.firebaseapp.com
ARG NEXT_PUBLIC_FIREBASE_PROJECT_ID=nexus0101-35b17
ARG NEXT_PUBLIC_FIREBASE_STORAGE_BUCKET=nexus0101-35b17.firebasestorage.app
ARG NEXT_PUBLIC_FIREBASE_MESSAGING_SENDER_ID=555679529013
ARG NEXT_PUBLIC_FIREBASE_APP_ID=1:555679529013:web:e7d99746d15d6abc09597c
ARG NEXT_PUBLIC_FIREBASE_MEASUREMENT_ID=G-X8MYN8L7TL
ARG NEXT_PUBLIC_FIREBASE_USE_EMULATOR=false
ARG NEXT_PUBLIC_FIREBASE_ADMIN_UIDS=51akf8KsWJdAJpkBQ036GMAXhhM2,WDTffv63Z1WlAoxagpP4OQBv1AM2,M1KErU2Og4UZCpICSZoyKKt2A7c2

ENV NEXT_PUBLIC_FIREBASE_API_KEY=${NEXT_PUBLIC_FIREBASE_API_KEY}
ENV NEXT_PUBLIC_FIREBASE_AUTH_DOMAIN=${NEXT_PUBLIC_FIREBASE_AUTH_DOMAIN}
ENV NEXT_PUBLIC_FIREBASE_PROJECT_ID=${NEXT_PUBLIC_FIREBASE_PROJECT_ID}
ENV NEXT_PUBLIC_FIREBASE_STORAGE_BUCKET=${NEXT_PUBLIC_FIREBASE_STORAGE_BUCKET}
ENV NEXT_PUBLIC_FIREBASE_MESSAGING_SENDER_ID=${NEXT_PUBLIC_FIREBASE_MESSAGING_SENDER_ID}
ENV NEXT_PUBLIC_FIREBASE_APP_ID=${NEXT_PUBLIC_FIREBASE_APP_ID}
ENV NEXT_PUBLIC_FIREBASE_MEASUREMENT_ID=${NEXT_PUBLIC_FIREBASE_MEASUREMENT_ID}
ENV NEXT_PUBLIC_FIREBASE_USE_EMULATOR=${NEXT_PUBLIC_FIREBASE_USE_EMULATOR}
ENV NEXT_PUBLIC_FIREBASE_ADMIN_UIDS=${NEXT_PUBLIC_FIREBASE_ADMIN_UIDS}

RUN npm run build \
  && npm prune --omit=dev

ENV NODE_ENV=production
ENV PROOFREAD_PYTHON=/opt/venv/bin/python

EXPOSE 3000
CMD ["npm", "run", "start"]
